#!/usr/bin/env python3
"""arch-probe -- the per-GPU numerical fingerprint, in about ninety seconds.

Runs ON a rented box.  Everything it computes is a pure function of
(deterministic inputs, torch build, GPU), so two boxes that print the same
digests did the same arithmetic, and two that do not, did not.

Layers, cheapest first, so a divergence can be LOCALISED rather than guessed at:

  L1  elementwise + transcendentals   exp/log/tanh/rsqrt/erf/sigmoid
  L2  GEMM                       bf16 / fp16 / fp32(tf32 off) / fp32(tf32 on) /
                                 fp64, at a square shape, the streaming lane's
                                 own skinny expert shape, and a split-k-bait
                                 tall-thin shape
  L3  grouped GEMM               torch.nn.functional.grouped_mm -- the MoE
                                 kernel the streaming lane actually dispatches
  L4  reductions                 sum/mean/logsumexp over dim=-1 and dim=0,
                                 fp32 + fp64, at 8k and at the real 154880 vocab
  L5  softmax family             softmax / log_softmax fp32 + fp64
  L6  the scorer's own reduction k6_kld_report._token_kld, verbatim, on
                                 SYNTHETIC logits at the real vocab width
  L7  a transformer forward      a fixed-weight 16-layer decoder, hidden states
                                 kept at every depth so divergence-vs-depth is
                                 measurable
  L8  reduction-split sweep      the same fp64 last-dim sum at 11 row counts and
                                 16384 columns
  L9  the same, at 154880 cols   the real vocabulary width, where ATen's
                                 device-derived reduction split actually
                                 engages -- this locates the row count at which
                                 two cards stop agreeing
  L10 the scorer at four chunks  _token_kld verbatim at 256/512/640/1024
                                 positions: does raising the lane's
                                 --chunk-positions past the split threshold
                                 make every card agree?

Every input tensor is generated by numpy's PCG64 (bit-reproducible across
platforms) on the CPU and hashed, so "the two boxes were fed the same bytes" is
evidence rather than an assumption.

Run it TWICE per box -- once plain, once as

    CUBLAS_WORKSPACE_CONFIG=:4096:8 python3 probe_payload.py --deterministic

-- because `torch.use_deterministic_algorithms` and the cuBLAS workspace pin
must be in place BEFORE the cuBLAS handle exists, which a flag flipped
mid-process cannot do.  That pair answers "does forcing determinism make two
ARCHITECTURES agree" with the same artifact that asks it.

Stock torch + numpy; no installs, no network, no model download.
"""
import argparse
import hashlib
import json
import os
import platform
import subprocess
import sys
import time

import numpy as np
import torch

SCHEMA = "malaiwah.arch-determinism-probe.v1"

VOCAB_REAL = 154880          # GLM-5.3-Flash's vocabulary
KLD_POSITIONS = 512          # the lane's --chunk-positions
KLD_CPU_ROWS = 64            # the CPU cross-check runs on a slice; fp64 CPU is slow

# The toy decoder: small enough for a 16 GB card, deep enough that depth is a
# variable rather than a footnote.
TOY = dict(layers=16, hidden=1024, heads=16, ffn=4096, vocab=32768, seq=256)


def sha(x) -> str:
    if isinstance(x, torch.Tensor):
        x = x.detach().to("cpu").contiguous()
        if x.dtype is torch.bfloat16:
            # numpy has no bfloat16; view the raw 16 bits so nothing is rounded
            # on the way to the digest.
            x = x.view(torch.int16)
        x = x.numpy()
    return hashlib.sha256(np.ascontiguousarray(x).tobytes()).hexdigest()


def rng(seed):
    return np.random.Generator(np.random.PCG64(seed))


def normal(seed, *shape, scale=1.0):
    """fp32 inputs from a bit-reproducible generator, identical on every host."""
    return rng(seed).standard_normal(size=shape, dtype=np.float32) * np.float32(scale)


def _driver():
    try:
        return subprocess.run(
            ["nvidia-smi", "--query-gpu=driver_version", "--format=csv,noheader"],
            capture_output=True, text=True, timeout=30).stdout.strip()
    except Exception as exc:                                      # noqa: BLE001
        return "unknown (%s)" % str(exc)[:60]


def lane_policy():
    """Exactly what k6/tools/stream_score.py sets before it captures."""
    torch.backends.cuda.matmul.allow_tf32 = False
    torch.backends.cudnn.allow_tf32 = False
    torch.set_float32_matmul_precision("highest")


# ---------------------------------------------------------------------------
# L1 .. L5 -- the primitive battery
# ---------------------------------------------------------------------------
def battery(dev, out):
    # L1 elementwise / transcendental --------------------------------------
    v = torch.from_numpy(normal(101, 1 << 20)).to(dev)
    out["L1.in"] = sha(v)
    for name, fn in (("exp", torch.exp),
                     ("log", lambda t: torch.log(t.abs() + 1e-6)),
                     ("tanh", torch.tanh),
                     ("rsqrt", lambda t: torch.rsqrt(t.abs() + 1e-6)),
                     ("erf", torch.erf),
                     ("sigmoid", torch.sigmoid)):
        out["L1.%s.fp32" % name] = sha(fn(v))
        out["L1.%s.fp64" % name] = sha(fn(v.double()))
    del v

    # L2 GEMM ---------------------------------------------------------------
    for tag, (m, k, n) in (("sq2048", (2048, 2048, 2048)),
                           ("expert", (2047, 4096, 2048)),
                           ("splitk", (256, 16384, 256))):
        a32 = torch.from_numpy(normal(201, m, k)).to(dev)
        b32 = torch.from_numpy(normal(202, k, n)).to(dev)
        out["L2.%s.in_a" % tag] = sha(a32)
        out["L2.%s.in_b" % tag] = sha(b32)
        out["L2.%s.bf16" % tag] = sha(a32.bfloat16() @ b32.bfloat16())
        out["L2.%s.fp16" % tag] = sha(a32.half() @ b32.half())
        lane_policy()
        out["L2.%s.fp32_tf32off" % tag] = sha(a32 @ b32)
        torch.backends.cuda.matmul.allow_tf32 = True
        torch.set_float32_matmul_precision("high")
        out["L2.%s.fp32_tf32on" % tag] = sha(a32 @ b32)
        lane_policy()
        out["L2.%s.fp64" % tag] = sha(a32.double() @ b32.double())
        del a32, b32
        torch.cuda.empty_cache()

    # L3 grouped GEMM -- the kernel the lane's MoE forward really dispatches --
    gm = getattr(torch.nn.functional, "grouped_mm", None)
    if gm is None:
        out["L3.grouped_mm"] = "absent-in-this-torch"
    else:
        try:
            groups, m, k, n = 8, 256, 1024, 1024
            a = torch.from_numpy(normal(301, groups * m, k)).to(dev).bfloat16()
            b = torch.from_numpy(normal(302, groups, k, n)).to(dev).bfloat16()
            offs = torch.arange(1, groups + 1, device=dev, dtype=torch.int32) * m
            out["L3.grouped_mm.in_a"] = sha(a)
            out["L3.grouped_mm.in_b"] = sha(b)
            out["L3.grouped_mm"] = sha(gm(a, b, offs=offs))
            # the same arithmetic as `groups` separate matmuls: if these two
            # disagree the grouped kernel is not merely a loop.
            out["L3.loop_mm"] = sha(torch.cat(
                [a[i * m:(i + 1) * m] @ b[i] for i in range(groups)], dim=0))
            del a, b, offs
            torch.cuda.empty_cache()
        except Exception as exc:                                  # noqa: BLE001
            out["L3.grouped_mm"] = "failed: %s" % str(exc)[:160]

    # L4 reductions ---------------------------------------------------------
    # The last dim is the axis k6_kld_report reduces over, and the axis whose
    # CUDA block/split configuration is chosen from the device's SM count.
    r = torch.from_numpy(normal(401, 512, 8192)).to(dev)
    out["L4.in"] = sha(r)
    for dt, tag in ((torch.float32, "fp32"), (torch.float64, "fp64")):
        x = r.to(dt)
        out["L4.sum_lastdim.%s" % tag] = sha(x.sum(dim=-1))
        out["L4.sum_dim0.%s" % tag] = sha(x.sum(dim=0))
        out["L4.mean_lastdim.%s" % tag] = sha(x.mean(dim=-1))
        out["L4.sum_all.%s" % tag] = sha(x.sum())
        out["L4.logsumexp.%s" % tag] = sha(torch.logsumexp(x, dim=-1))
        del x
    del r
    torch.cuda.empty_cache()
    # the same reduction at the REAL vocabulary width, where the split
    # heuristic has far more to choose between
    w = torch.from_numpy(normal(402, 64, VOCAB_REAL)).to(dev)
    out["L4.wide.in"] = sha(w)
    out["L4.wide.sum_lastdim.fp64"] = sha(w.double().sum(dim=-1))
    out["L4.wide.logsumexp.fp64"] = sha(torch.logsumexp(w.double(), dim=-1))
    del w
    torch.cuda.empty_cache()

    # L5 softmax family -----------------------------------------------------
    s = torch.from_numpy(normal(501, 256, VOCAB_REAL)).to(dev)
    out["L5.in"] = sha(s)
    out["L5.softmax.fp32"] = sha(torch.softmax(s, dim=-1))
    out["L5.log_softmax.fp32"] = sha(torch.log_softmax(s, dim=-1))
    s64 = s.double()
    out["L5.softmax.fp64"] = sha(torch.softmax(s64, dim=-1))
    out["L5.log_softmax.fp64"] = sha(torch.log_softmax(s64, dim=-1))
    del s, s64
    torch.cuda.empty_cache()
    return out


# ---------------------------------------------------------------------------
# L6 -- the scorer's own reduction, verbatim
# ---------------------------------------------------------------------------
def token_kld(teacher, student, device):
    """Copied from k6/tools/k6_kld_report.py::_token_kld -- do not 'improve'."""
    teacher64 = teacher.to(device=device, dtype=torch.float64)
    student64 = student.to(device=device, dtype=torch.float64)
    teacher_logp = torch.log_softmax(teacher64, dim=-1)
    student_logp = torch.log_softmax(student64, dim=-1)
    values = torch.sum(torch.exp(teacher_logp) * (teacher_logp - student_logp), dim=-1)
    matches = int(torch.count_nonzero(
        torch.argmax(teacher64, dim=-1) == torch.argmax(student64, dim=-1)))
    return values.cpu().numpy(), matches


def kld_layer(dev):
    """Feed the scorer's reduction IDENTICAL fp32 logits on every box.

    If this digest moves between architectures, the reported KLD can move even
    when the student forward did not.  If it does not move, the reduction is
    exonerated and the divergence is upstream of it.
    """
    t = torch.from_numpy(normal(601, KLD_POSITIONS, VOCAB_REAL, scale=4.0))
    s = torch.from_numpy(normal(602, KLD_POSITIONS, VOCAB_REAL, scale=4.0))
    s = t * np.float32(0.97) + s * np.float32(0.03)
    values, matches = token_kld(t, s, dev)
    cpu_values, cpu_matches = token_kld(t[:KLD_CPU_ROWS], s[:KLD_CPU_ROWS], "cpu")
    res = {
        "L6.teacher_in": sha(t),
        "L6.student_in": sha(s),
        "L6.tokenwise_kld": sha(values),
        "L6.mean": repr(float(values.mean())),
        "L6.top1_matches": matches,
        "L6.tokenwise_kld_cpu_slice": sha(cpu_values),
        "L6.top1_matches_cpu_slice": cpu_matches,
        "L6.cuda_slice_equals_cpu_slice": bool(
            sha(values[:KLD_CPU_ROWS]) == sha(cpu_values)),
    }
    del t, s
    torch.cuda.empty_cache()
    return res, values


# ---------------------------------------------------------------------------
# L7 -- a real forward, with depth as a variable
# ---------------------------------------------------------------------------
class ToyWeights:
    """Fixed weights from PCG64, so the model is the same object everywhere."""

    def __init__(self, dev, dtype):
        h, f, v, L = TOY["hidden"], TOY["ffn"], TOY["vocab"], TOY["layers"]

        def g(seed, *s, sc=1.0):
            return torch.from_numpy(normal(seed, *s, scale=sc)).to(dev).to(dtype)

        self.emb = g(700, v, h, sc=0.02)
        self.layers = [dict(
            wq=g(710 + i * 7, h, h, sc=h ** -0.5),
            wk=g(711 + i * 7, h, h, sc=h ** -0.5),
            wv=g(712 + i * 7, h, h, sc=h ** -0.5),
            wo=g(713 + i * 7, h, h, sc=h ** -0.5),
            w1=g(714 + i * 7, h, f, sc=h ** -0.5),
            w2=g(715 + i * 7, f, h, sc=f ** -0.5),
        ) for i in range(L)]
        self.head = g(900, h, v, sc=h ** -0.5)


def rmsnorm(x):
    f = x.float()
    return (f * torch.rsqrt(f.pow(2).mean(-1, keepdim=True) + 1e-6)).to(x.dtype)


def toy_forward(w, tokens, dev, dtype):
    """Pre-norm decoder, eager attention -- the lane's own attention backend."""
    h, heads = TOY["hidden"], TOY["heads"]
    hd = h // heads
    x = w.emb[tokens].to(dtype)
    S = x.shape[0]
    mask = torch.full((S, S), float("-inf"), device=dev, dtype=torch.float32).triu(1)
    depths = {}
    for i, p in enumerate(w.layers):
        n = rmsnorm(x)
        q = (n @ p["wq"]).view(S, heads, hd).transpose(0, 1)
        k = (n @ p["wk"]).view(S, heads, hd).transpose(0, 1)
        v = (n @ p["wv"]).view(S, heads, hd).transpose(0, 1)
        att = (q.float() @ k.float().transpose(-1, -2)) * (hd ** -0.5) + mask
        att = torch.softmax(att, dim=-1).to(dtype)
        o = (att @ v).transpose(0, 1).reshape(S, h) @ p["wo"]
        x = x + o
        n = rmsnorm(x)
        x = x + (torch.nn.functional.silu(n @ p["w1"]) @ p["w2"])
        depths["depth%02d" % (i + 1)] = x.float().detach().to("cpu").numpy().copy()
    logits = (rmsnorm(x) @ w.head).float()
    return logits.detach().to("cpu").numpy().copy(), depths


def forward_layer(dev, keep_tensors):
    tokens = torch.from_numpy(
        rng(999).integers(0, TOY["vocab"], size=TOY["seq"]).astype(np.int64)).to(dev)
    res, tensors = {}, {}
    res["L7.tokens"] = sha(tokens.cpu().numpy())
    for dtype, tag in ((torch.bfloat16, "bf16"), (torch.float32, "fp32")):
        w = ToyWeights(dev, dtype)
        res["L7.%s.emb_in" % tag] = sha(w.emb)
        logits, depths = toy_forward(w, tokens, dev, dtype)
        res["L7.%s.logits" % tag] = sha(logits)
        for name, arr in depths.items():
            res["L7.%s.%s" % (tag, name)] = sha(arr)
        if keep_tensors:
            tensors["logits_%s" % tag] = logits
            if tag == "bf16":
                # the dtype the streaming lane runs; 16 fp32 depth slabs = 16 MB
                for name, arr in depths.items():
                    tensors["h_%s" % name] = arr
        del w
        torch.cuda.empty_cache()
    return res, tensors


# ---------------------------------------------------------------------------
# L8 -- where the reduction splits, and what decides it
# ---------------------------------------------------------------------------
# ATen picks a CUDA reduction configuration from the DEVICE, not from the data:
# when the number of output rows is small relative to the SM count it splits
# each row's sum across several blocks and combines them, which changes the
# ORDER of an fp64 addition chain and therefore its last bits. Sweeping the row
# count on every card turns "architecture-dependent" into a number: the row
# count at which two cards stop agreeing.
L8_COLS = 16384
L8_ROWS = (16, 32, 64, 96, 128, 192, 256, 384, 512, 768, 1024)
# L9 repeats the sweep at the REAL vocabulary width. That matters: a moderate
# reduction length gives the split heuristic nothing to win, so L8 is flat on
# every card, and only at 154880 columns does the device-derived split appear.
L9_COLS = VOCAB_REAL
L9_ROWS = (32, 64, 128, 256, 384, 448, 512, 640, 768, 1024)


def _sweep(dev, out, tag, cols, rows_list, seed):
    for rows in rows_list:
        x = torch.from_numpy(normal(seed, rows, cols)).to(dev)
        out["%s.rows%04d.in" % (tag, rows)] = sha(x)
        x64 = x.double()
        out["%s.rows%04d.sum_lastdim.fp64" % (tag, rows)] = sha(x64.sum(dim=-1))
        out["%s.rows%04d.sum_lastdim.fp32" % (tag, rows)] = sha(x.sum(dim=-1))
        del x, x64
        torch.cuda.empty_cache()
    return out


# L10 asks the operational question directly: does the SCORER's own estimator
# -- k6_kld_report._token_kld, verbatim -- stop being device-dependent if the
# position block is raised past the row count at which ATen stops splitting the
# reduction? `--chunk-positions 512` is what the streaming lane runs today.
L10_CHUNKS = (256, 512, 640, 1024)


def kld_chunk_sweep(dev, out):
    for rows in L10_CHUNKS:
        t = torch.from_numpy(normal(601, rows, VOCAB_REAL, scale=4.0))
        s = torch.from_numpy(normal(602, rows, VOCAB_REAL, scale=4.0))
        s = t * np.float32(0.97) + s * np.float32(0.03)
        out["L10.chunk%04d.in_t" % rows] = sha(t)
        out["L10.chunk%04d.in_s" % rows] = sha(s)
        values, matches = token_kld(t, s, dev)
        out["L10.chunk%04d.tokenwise_kld" % rows] = sha(values)
        out["L10.chunk%04d.mean" % rows] = repr(float(values.mean()))
        del t, s
        torch.cuda.empty_cache()
    return out


def reduction_sweep(dev, out):
    _sweep(dev, out, "L8", L8_COLS, L8_ROWS, 801)
    _sweep(dev, out, "L9", L9_COLS, L9_ROWS, 901)
    kld_chunk_sweep(dev, out)
    return out


# ---------------------------------------------------------------------------
def main(argv=None):
    ap = argparse.ArgumentParser(prog="arch-probe")
    ap.add_argument("--out", default="/tmp/archprobe")
    ap.add_argument("--deterministic", action="store_true",
                    help="torch.use_deterministic_algorithms(True); pair it with "
                         "CUBLAS_WORKSPACE_CONFIG set in the ENVIRONMENT")
    ap.add_argument("--no-tensors", action="store_true")
    ap.add_argument("--sweep-only", action="store_true",
                    help="run only the L8/L9 reduction sweeps")
    ap.add_argument("--device", default="cuda",
                    help="SMOKE TEST ONLY: 'cpu' exercises every code path off a "
                         "GPU. A cpu run is not a fingerprint of anything.")
    args = ap.parse_args(argv)

    if args.device == "cuda" and not torch.cuda.is_available():
        print(json.dumps({"error": "no cuda"}))
        return 1
    os.makedirs(args.out, exist_ok=True)
    dev = torch.device(args.device)
    started = time.time()

    det_status = "off"
    if args.deterministic:
        try:
            torch.use_deterministic_algorithms(True, warn_only=True)
            det_status = "on"
        except Exception as exc:                                  # noqa: BLE001
            det_status = "failed: %s" % str(exc)[:160]
    lane_policy()

    if dev.type == "cuda":
        p = torch.cuda.get_device_properties(0)
        ident = {
            "name": torch.cuda.get_device_name(0),
            "capability": "sm_%d%d" % (p.major, p.minor),
            "sm_major": p.major,
            "sm_minor": p.minor,
            "multi_processor_count": p.multi_processor_count,
            "max_threads_per_multi_processor": getattr(
                p, "max_threads_per_multi_processor", None),
            "warp_size": getattr(p, "warp_size", None),
            "l2_cache_size": getattr(p, "L2_cache_size", None),
            "total_memory_gb": round(p.total_memory / 1024 ** 3, 2),
            "driver": _driver(),
        }
    else:
        ident = {"name": "cpu-smoke", "capability": None, "sm_major": None,
                 "sm_minor": None, "multi_processor_count": None,
                 "total_memory_gb": None, "driver": None}

    doc = {
        "schema": SCHEMA,
        "device": ident,
        "stack": {
            "torch": torch.__version__,
            "torch_cuda": torch.version.cuda,
            "cudnn": torch.backends.cudnn.version(),
            "numpy": np.__version__,
            "python": platform.python_version(),
            "platform": platform.platform(),
            "cublas_workspace_config": os.environ.get("CUBLAS_WORKSPACE_CONFIG"),
            "nvidia_tf32_override": os.environ.get("NVIDIA_TF32_OVERRIDE"),
        },
        "mode": {
            "deterministic_algorithms": det_status,
            "allow_tf32_cuda_matmul": torch.backends.cuda.matmul.allow_tf32,
            "allow_tf32_cudnn": torch.backends.cudnn.allow_tf32,
            "float32_matmul_precision": torch.get_float32_matmul_precision(),
        },
        "toy_model": dict(TOY),
    }

    digests = {}
    tensors = {}
    if args.sweep_only:
        reduction_sweep(dev, digests)
    else:
        battery(dev, digests)
        reduction_sweep(dev, digests)
        kld, kld_values = kld_layer(dev)
        digests.update(kld)
        fwd, t = forward_layer(dev, keep_tensors=not args.no_tensors)
        digests.update(fwd)
        tensors.update(t)
        tensors["tokenwise_kld_L6"] = kld_values
    doc["digests"] = digests
    doc["elapsed_seconds"] = round(time.time() - started, 1)

    if not args.no_tensors and tensors:
        path = os.path.join(args.out, "probe-tensors.npz")
        np.savez(path, **tensors)
        with open(path, "rb") as fh:
            doc["tensors_file_sha256"] = hashlib.sha256(fh.read()).hexdigest()

    with open(os.path.join(args.out, "probe.json"), "w") as fh:
        json.dump(doc, fh, indent=1, sort_keys=True)
    print("ARCHPROBE_JSON_BEGIN")
    print(json.dumps(doc, sort_keys=True))
    print("ARCHPROBE_JSON_END")
    return 0


if __name__ == "__main__":
    sys.exit(main())
